---
title: "Data Cleaning"
author: "Tyler Jackson"
date: "7/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(igraph)
library(stringr)
```


```{r data}

#read in the data from Matt, needs cleaning
clist <- read.csv("./data/centerContactList.csv")

dim(clist)
head(clist[3:13,])

nodes <- clist[,3:13]

names(nodes)

#created a dummy variable to aggregate by
clist$null <- ""

#aggregate and add to nodes
center.ppl <- aggregate(null ~ CenterPerson + CenterRole, data = clist,
                        FUN = nrow) 

names(center.ppl) <- c('Contact', 'Role')

names(center.ppl)
nodes <- rbind(nodes, center.ppl[,1:2])



center.ppl$Contact <- as.character(center.ppl$Contact)
center.ppl$Role <- as.character(center.ppl$Role)

nodes <- bind_rows(nodes, center.ppl[,1:2])
          
names(nodes)
names(clist)

#create an edge list
edges <- bind_cols(clist[,c(1,3)])

names(edges) <- c('source', 'target')

names(nodes)
#write nodes and edges to csv
```

```{r}
#read in written from above
nodes <- read.csv("nodes.csv")
edges <- read.csv("edges.csv")

edges$target <- str_trim(edges$target)

edges$target
nodes$Contact

nodes$Contact <- str_trim(nodes$Contact)

contact.fq <- table(nodes$Contact)

contact.fq <- as.data.frame(contact.fq)

dupes <- contact.fq[contact.fq$Freq > 1,]$Var1

dupes

for (i in dupes){
  num <- which(nodes$Contact == i)
  print(num)
}#48, 353 / 28, 116

nodes <- nodes[-c(28, 48),]

nodes$Contact <- as.character(nodes$Contact)
edges$source <- as.character(edges$source)
edges$target <- as.character(edges$target)

nodes$X.1 <- NULL
edges$X <- NULL

write.csv(edges, "edges.csv", row.names = F)
write.csv(nodes, "nodes.csv", row.names = F)
```



